name: Generate Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

# Allow concurrent runs, but cancel previous runs on new commits
concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-docs:
    name: Generate Documentation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz cmake ninja-build
        # Install newer CMake to ensure compatibility
        CMAKE_VERSION="4.1.1"
        wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
        sudo apt-add-repository "deb https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main"
        sudo apt-get update
        sudo apt-get install -y cmake=${CMAKE_VERSION}* cmake-data=${CMAKE_VERSION}*

    - name: Configure CMake
      run: |
        cmake --preset ninja-mc -DSDL_UNIX_CONSOLE_BUILD=ON

    - name: Generate documentation
      run: |
        cmake --build --preset ninja-mc-debug --target docs

    - name: Upload documentation artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: documentation
        path: build/ninja-mc/docs/output/html/
        retention-days: 90